[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-LightControl-TPLink"
version = "2.0.0"
description = "Adds TPLink Smart Plug support to OctoPrint-LightControl as a sub-plugin."
authors = [
    {name = "Alerick Beaman", email = "35195829+arbeaman@users.noreply.github.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
dynamic = ["license"]
requires-python = ">=3.7, <4"

# any additional requirements besides OctoPrint should be listed here
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_lightcontrol_tplink",
    "octoprint_lightcontrol_tplink.*"
]

[project.entry-points."octoprint.plugin"]
lightcontrol_tplink = "octoprint_lightcontrol_tplink"

[project.urls]
Homepage = "https://github.com/arbeaman/OctoPrint-LightControl-TPLink"
